# Generated by Django 2.2.13 on 2020-11-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsettings',
            name='UsePredefinedModel',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassSetsRadio', models.CharField(max_length=15)),
                ('ClassSets', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_class_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
