# Generated by Django 2.2.13 on 2020-12-01 16:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_settings', '0004_auto_20201130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsettings',
            name='ClassSets',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='MailLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whiteList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('blackList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mail_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
