# Generated by Django 2.2.13 on 2020-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0008_auto_20201201_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillists',
            name='blackList',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maillists',
            name='whiteList',
            field=models.TextField(blank=True, null=True),
        ),
    ]
