# Generated by Django 2.2.13 on 2021-04-26 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_settings', '0009_auto_20201201_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLearn', models.CharField(max_length=30)),
                ('totalTime', models.CharField(max_length=30)),
                ('VolumeInbox', models.IntegerField()),
                ('VolumeSpam', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lastlearn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
